import React from "react";
import image1 from "../../assets/20.png";
import image2 from "../../assets/21.png";
import image3 from "../../assets/22.png";
import image4 from "../../assets/23.png";
import "./belowTopSection.css";

const BelowTopSection = () => {
  return (
    <div className="below-topsection-main-wrapper">
      <div className="belowtopsettion-inner-wrapper">
        <div className="belowtop-inner-box-left">
          <div className="below-inner-left-top">
            <img src={image1} alt="image1" />
          </div>
          <div className="below-inner-left-bottom">
            <div>
              <img src={image2} alt="image2" />
            </div>
            <div className="right">
              <img src={image3} alt="image3" />
            </div>
          </div>
        </div>
        <div className="belowtop-inner-box-right">
          <div className="bellowtop-inner-right-top">
            <div className="textbox">
              <h2>What are GoosePunks?</h2>
              <p>
                GoosePunks is a collection of unique NFT avatars. This series is
                called GoosePunks Renegades Each GoosePunk is algorithmically
                generated by randomly combining together numerous professionally
                illustrated properties across various categories. There are more
                than 1,100 inside the algorithm! When you own a GoosePunk you
                have full ownership over this character. Ownership of a
                GoosePunk is your exclusive invitation into the Khena Metaverse.
                Read more below.
              </p>
            </div>
          </div>
          <div className="bellowtop-inner-right-bottom">
            <div className="below-img-wrapper">
              <img src={image4} alt="image4" />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default BelowTopSection;
